### PR TITLE
Fix data-uri (issue #38)

### PR DESCRIPTION
**Pull request by next0**
Fix issue #38 :

```
Module build failed: error evaluating function `data-uri`: Cannot 'resolveSync' because the fileSystem is not sync. Use 'resolve'!
```

### CODE REVIEW

**Comment by ericmatthys** [comment]
This fixes the `data-uri` issue in my project. :+1:

**Comment by revolunet** [comment]
yes please :)

**Comment by XiXora** [comment]
+1

**Comment by jeantroiani** [comment]
+1

**Comment by andresgarza** [comment]
+1

**Comment by ftdebugger** [comment]
Merge please

**Comment by criyology** [comment]
+1

**Comment by vlyahovich** [comment]
+1

**Comment by antejan** [comment]
+1

**Comment by romka-bear** [comment]
+1

**Comment by NeXidan** [comment]
:+1:

**Comment by DenisHomich** [comment]
+1

**Comment by dontuncleme** [comment]
+1

**Comment by Tocher** [comment]
:+1:

**Comment by lifus** [comment]
+1

**Comment by nchereva** [comment]
:+1:

**Comment by dorsha** [comment]
+1

**Comment by sokra** [comment]
Thanks

**Comment by revolunet** [comment]
thanks

**Comment by jhnns** [comment]
@next0 Awesome! You've even included tests :+1:

**Comment by jhnns** [comment]
Fix shipped with `2.2.2`

**Pull request merged**
