### PR TITLE
Configure Less to create source maps

### LINKED ISSUE #16: Create source maps
It would be very helpful if there was some way to emit source maps for .less files.

### PR DESCRIPTION
**Pull request by mtscout6**
Fixes #16

### CODE REVIEW

**Comment by mtscout6** [comment]
Hold off a bit on this I just found out that images are no longer coming through on my sight with this change. I'll dig into more on Monday.

**Comment by jhnns** [comment]
Looking forward to merge it :+1:  :grinning:

**Comment by sokra** [comment]
Looks good :+1:

**Comment by mtscout6** [comment]
Sorry for the delay in checking this further I've been tied up all week dealing with a bug on an internal tool. I'm nearly done with that issue so I will get back to figuring out what's going on with the images sometime next week. Though it may be related to webpack/css-loader#40. I had this change as well as that one derive sourcemap settings from the webpack `devtool` setting instead of through query params, so that may be all that's needed. I'm also not taking advantage of the extract-text-plugin yet which may also be part of my problem.

**Comment by mtscout6** [comment]
The background image issue I'm having is definitely related to webpack/css-loader#40. I'd still like to have the benefit of having the source map setting pulled from the webpack config `devtool` setting though. What are your thoughts around having the extract text plugin dynamically apply that `sourceMap` query option based on the webpack `devtool` configuration? This would allow the `webpack -d` option to work only when using that plugin, otherwise users would need to explicitly turn it on as they do now.

**Comment by mtscout6** [comment]
@sokra I'm confident that this is good to go, the image problem was with my fork of the css-loader I was using.

**Comment by mtscout6** [comment]
bump

**Comment by jdaudier** [comment]
This seems related to https://github.com/webpack/less-loader/pull/33

I would love to use this feature to generate sourcemap of the less files.

**Comment by mtscout6** [comment]
It is related to #33 with changes as per @sokra's requests.

**Comment by jdaudier** [comment]
i hope this gets merged soon! :smile:

**Comment by jhnns** [comment]
Published with `2.1.0`.

**Careful**: Source maps are only available with the `?sourceMap` query. I'm not using the `this.sourceMap` flag because CSS source maps need to be treated different. See the discussion https://github.com/webpack/css-loader/pull/40

[Checkout the README](https://github.com/webpack/less-loader#source-maps) for an explanation how to use source maps.

**Comment by mtscout6** [comment]
@jhnns I left it as `this.sourceMap` primarily due to the conversation in webpack/extract-text-webpack-plugin#53

**Comment by jdaudier** [comment]
So this works if I don't use `webpack.optimize.UglifyJsPlugin`.  Is there a way to make it work with that plugin running?

**Pull request merged**
