### PR TITLE
docs(README): refactor for webpack v2

### PR DESCRIPTION
**Pull request by michael-ciniawsky**
⚠️  WIP - Do not merge  ⚠️ 

[README](https://github.com/michael-ciniawsky/less-loader/tree/readme)

@webpack/core-team @webpack/contributor-team

### CODE REVIEW

**Comment by SpaceK33z** [comment]
@michael-ciniawsky, hey I've pushed some small changes:

- Moved the "Configuration" way to configure the loader to the top, since it is recommended.
- Added semi-colons at the end of some JS lines, I know that some from the core team really don't like stuff without semi-colons ;).
- Converted to ES Modules in application code.
- Added `-loader` to the "Require way", since it doesn't work without anymore in v2.

**Comment by michael-ciniawsky** [comment]
> Moved the "Configuration" way to configure the loader to the top, since it is recommended.

👍 Update that on the README's

> Added semi-colons at the end of some JS lines, I know that some from the core team really don't like stuff without semi-colons ;).

Oops 😛 . I'm StandardJS advocat, I will add them, but no guarantee I will not miss one here and there

> Converted to ES Modules in application code.

👍 

> Added -loader to the "Require way", since it doesn't work without anymore in v2.

😟  I know about it for `module.rules, but for 'inline' usage its really... ugly....  😢

Can't be helped, will update in other README's aswell :100:
Does this apply for CLI usage aswell ? `webpack --module-bind 'less=style-loader!css-loader!less-loader!`

**Comment by SpaceK33z** [comment]
> Does this apply for CLI usage aswell ? webpack --module-bind 'less=style-loader!css-loader!less-loader!

Oh forgot about fixing the CLI example, but yeah.

**Comment by SpaceK33z** [comment]
Fixed the CLI example. I think this is ready! Linking to https://github.com/webpack/webpack/issues/3195 for later.

**Pull request merged**
