### PR TITLE
Add support for source-maps

### PR DESCRIPTION
**Pull request by 3sv**
See https://github.com/3sv/webpack-less-autoprefixer-sourcemaps-demo for a demo. Can solve #16
No tests within this repo yet.

### CODE REVIEW

**Comment by sokra** [comment]
You can solve it without convert-source-map. less will give you the raw source-map with the correct options.

`sourceMap.file` should be `loaderUtils.getRemainingRequest(this)`
Use the fetched sources (from less filemanager) to fill `sourcesContent`. (Maybe apply source-map from loaded source, but this is difficult.)

cc @jhnns

**Comment by 3sv** [comment]
@sokra Don't know the webpack interface well enough. The getRemainingRequest produces a long filename with loader prefixes in it. This means that the maps need to be edited afterwards to produce clean/short filenames? What is the benefit of using the getRemainingRequest?

**Comment by sokra** [comment]
Oh I was wrong. `sourceMap.file` should be `loaderUtils.getCurrentRequest(this)`. It should point to the generated file. But I think is no used by webpack.

webpack preprocess all SourceMaps and try to map `sources` to module identifiers. It also shorten them an make it pretty. So you don't need about clean/short filenames.

But the most important change is to remove `convert-source-map`. less can (with the correct options) output a SourceMap object. It'll return `{code: ..., map: ...}`.

**Comment by mtscout6** [comment]
@3sv Here are the docs for having less create the sourcemaps for you: http://lesscss.org/usage/index.html#programmatic-usage

**Comment by mtscout6** [comment]
@sokra, I've gotta head out for the night, but I plan to keep on this tomorrow. Am I at least heading the right direction with [759481](https://github.com/mtscout6/less-loader/commit/759481c4eb1bfb22aa3c853244bd56084d78d347)?

**Comment by sokra** [comment]
yep

**Comment by jhnns** [comment]
After #36 being merged I think this PR is obsolete?

**Pull request closed without merging**
